spring:
  application:
    name: product


server:
  port: 9002

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

#redis相关配置
security:
  oauth2:
    resource:
      id: user-center
      user-info-uri: http://localhost:8080/api-o/user-me
      prefer-token-info: false

ribbon:
  eureka:
    enabled: true

  ReadTimeout: 60000
  ConnectTimeout: 60000