server:
  port: 9081

spring:
  application:
    name: log-center
  datasource:
    #如果报错The server time zone value '?й???׼ʱ?' is unrecognized or represents more than one time zone 需加&serverTimezone=UTC
    url: jdbc:mysql://localhost:3306/xidi?useSSL=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: linjiawei
    driver-class-name: com.mysql.cj.jdbc.Driver
es:
  clusterName: elasticsearch_linjiawei
  #es tcp地址 默认9300
  clusterNodes: localhost:9300

log-center:
  type: database

mybatis:
  configuration:
  #自动驼峰命名转换
      mapUnderscoreToCamelCase: true
      #打印mybatis执行sql
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mybatis-mappers/*.xml

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
