#认证中心
server:
  port: 9000
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/xidi?useSSL=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: linjiawei
    driver-class-name: com.mysql.cj.jdbc.Driver

    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      connection-test-query: SELECT 1

  redis:
    host: localhost
    port: 6379
    password:
    timeout: 5s

  zipkin:
    base-url: http://localhost:9411
    enabled: true
    sender:
      type: web
  sleuth:
    sampler:
      probability: 0.1

#存储token方式 redis/database 如果是database模式需预先创建好存放token的两张表 oauth_client_details、oauth_code
access_token_type: redis

management:
  endpoint:
    health:
      show-details: ALWAYS
    env:
      enabled: false
  endpoints:
    web:
      exposure:
        include: '*'
