#认证中心
server:
  port: 9000
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/actApp?useSSL=true&characterEncoding=utf8
    username: root
    password: linjiawei
    driver-class-name: com.mysql.cj.jdbc.Driver

#    hikari:
#      minimum-idle: 5
#      maximum-pool-size: 20
#      connection-test-query: SELECT 1

  redis:
    host: localhost
    port: 6379
    password:
    timeout: 5s

access_token:
  use-jwt: false

